# Generated by Django 4.1.2 on 2022-10-06 22:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Album', max_length=150)),
                ('creation_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('release_datetime', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
