# Generated by Django 4.1.2 on 2022-11-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
