# Generated by Django 4.1.2 on 2022-11-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
