# Generated by Django 4.1.2 on 2022-10-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
