# Generated by Django 4.1.2 on 2022-11-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
