# Generated by Django 4.1.2 on 2022-10-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_rename_is_approved_album_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
