# Generated by Django 4.1.2 on 2022-11-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
