# Generated by Django 4.1.2 on 2022-10-26 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_album_created_album_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='thumbs/')),
                ('audio', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
